name: Deploy OpenShift Cluster

on:
  workflow_dispatch:

jobs:
  deploy:
    name: OpenShift AWS Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change if you're using a different region

    - name: Install OpenShift Installer
      run: |
        curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux.tar.gz -o installer.tar.gz
        tar -xzf installer.tar.gz
        chmod +x openshift-install
        sudo mv openshift-install /usr/local/bin/

    - name: Create working directory
      run: mkdir -p ./openshift-cluster

    - name: Copy install-config
      run: cp ./install-config.yaml ./openshift-cluster/

    - name: Add pull secret and SSH key
      run: |
        echo '${{ secrets.PULL_SECRET }}' > ./openshift-cluster/pull-secret.txt
        echo '${{ secrets.SSH_PRIVATE_KEY }}' > ./openshift-cluster/ssh-key
        chmod 600 ./openshift-cluster/ssh-key

    - name: Run OpenShift Installer
      run: |
        cd openshift-cluster
        openshift-install create cluster --dir=. --log-level=info
