name: OpenShift Cluster Deployment

on:
  workflow_dispatch:

jobs:
  deploy-openshift:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenShift Installer
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux.tar.gz
          tar -xzf openshift-install-linux.tar.gz
          chmod +x openshift-install
          sudo mv openshift-install /usr/local/bin/

      - name: Create OpenShift cluster directory
        run: mkdir -p openshift-cluster

      - name: Generate install-config.yaml
        run: |
          echo "${{ secrets.OPENSHIFT_PULL_SECRET }}" > pull-secret.txt
          echo "${{ secrets.OPENSHIFT_SSH_KEY }}" > ssh-key.txt

          cat <<EOF > openshift-cluster/install-config.yaml
apiVersion: v1
baseDomain: example.com
metadata:
  name: mycluster
platform:
  aws:
    region: us-east-1
pullSecret: '$(cat pull-secret.txt)'
sshKey: '$(cat ssh-key.txt)'
EOF

      - name: Run OpenShift Installer
        run: |
          cd openshift-cluster
          openshift-install create cluster --dir=. --log-level=info
